| Name                       | Link                                                    | Description                                                                                     |
| -------------------------- | ------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| BrightCloud                | [https://brightcloud.com/tools/url-ip-lookup.php](https://brightcloud.com/tools/url-ip-lookup.php) | URL and IP lookup service providing threat intelligence.                                        |
| CheckPhish                 | [https://checkphish.ai/live-url-scan/](https://checkphish.ai/live-url-scan/)        | Real-time phishing detection using advanced machine learning.                                   |
| EasyDMARC                  | [https://easydmarc.com/tools/phishing-url](https://easydmarc.com/tools/phishing-url) | Tool for detecting phishing and enhancing email security.                                       |
| Email Veritas              | [https://emailveritas.com/url-checker](https://emailveritas.com/url-checker)        | URL checker for identifying malicious emails.                                                   |
| Trend Micro Site Safety    | [https://global.sitesafety.trendmicro.com/](https://global.sitesafety.trendmicro.com/) | Indexes the safety of websites across the web.                                                  |
| Hybrid Analysis            | [https://hybrid-analysis.com/](https://hybrid-analysis.com/)                         | Online malware analysis tool using hybrid techniques.                                           |
| MetaCert                   | [https://metacert.com/technology.html](https://metacert.com/technology.html)       | Technology solutions for securing apps and services.                                            |
| Norton Safe Web            | [https://safeweb.norton.com/](https://safeweb.norton.com/)                          | Norton's tool for checking website safety.                                                      |
| SafeToOpen                 | [https://scan.safetoopen.com/](https://scan.safetoopen.com/)                        | Scanner to ensure websites are safe to open.                                                    |
| ScanURL                    | [https://scanurl.net/](https://scanurl.net/)                                        | Provides an online tool to check the safety of URLs.                                            |
| Sucuri SiteCheck           | [https://sitecheck.sucuri.net/](https://sitecheck.sucuri.net/)                      | Scans websites for known issues and malware.                                                    |
| Talos Intelligence         | [https://talosintelligence.com/reputation_center/](https://talosintelligence.com/reputation_center/) | Cisco's platform for threat intelligence and reputation services.                               |
| Google Safe Browsing       | [https://transparencyreport.google.com/safe-browsing/search](https://transparencyreport.google.com/safe-browsing/search) | Google's tool to check URLs against known unsafe web resources.                                 |
| URLQuery                   | [https://urlquery.net/](https://urlquery.net/)                                      | A service to analyze websites for suspicious content.                                           |
| urlscan.io                 | [https://urlscan.io/](https://urlscan.io/)                                          | A sandbox-based URL and website scanner.                                                        |
| Criminal IP                | [https://www.criminalip.io/asset/search?query=](https://www.criminalip.io/asset/search?query=) | Search tool for analyzing and checking IP assets for malicious activity.                        |
| Get Safe Online            | [https://www.getsafeonline.org/checkawebsite/](https://www.getsafeonline.org/checkawebsite/) | Provides tips and tools to check website safety.                                                |
| IP Quality Score           | [https://www.ipqualityscore.com/threat-feeds/malicious-url-scanner](https://www.ipqualityscore.com/threat-feeds/malicious-url-scanner) | Malicious URL scanner for detecting unsafe websites.                                            |
| Joe Sandbox                | [https://www.joesandbox.com/#windows](https://www.joesandbox.com/#windows)          | Deep analysis tool to detect and analyze potential threats on Windows systems.                  |
| dfndr lab                  | [https://www.psafe.com/dfndr-lab/](https://www.psafe.com/dfndr-lab/)                | dfndr lab's tool for real-time analysis of cyber threats.                                       |
| ScamAdviser                | [https://www.scamadviser.com/](https://www.scamadviser.com/)                         | Checks the trust score of websites to detect scams.                                             |
| SiteLock                   | [https://www.sitelock.com/free-website-scan/](https://www.sitelock.com/free-website-scan/) | Free tool for scanning websites for vulnerabilities and malware.                                |
| URLVoid                    | [https://www.urlvoid.com/](https://www.urlvoid.com/)                                | Service to check a website's reputation using multiple scanning engines.                        |
| VirusTotal                 | [https://www.virustotal.com/gui/home/url](https://www.virustotal.com/gui/home/url)  | Analyzes suspicious URLs and files to detect types of malware.                                  |
| Zscaler Zulu               | [https://zulu.zscaler.com/](https://zulu.zscaler.com/)                              | Zscaler's Zulu URL Risk Analyzer.                                                               |
| URL Score                  | [https://urlscore.ai/](https://urlscore.ai/)                                        | AI-powered tool for URL analysis and threat detection.                                          |
